apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-short-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: api-short
          image: antonlarichev/short-api
          resources:
            limits:
              memory: '228Mi'
              cpu: '200m'
          ports:
            - containerPort: 3000
