apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" 
  .Values.db.user 
  .Values.db.password 
  .Values.db.host 
  (.Values.postgres.port | int64)
  .Values.db.db | b64enc | quote }}
