apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-clusterip
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.app.components }}
  ports:
    - port: {{ .Values.app.port }}
      protocol: TCP
