apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clusterip
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.postgres.components }}
  ports:
    - port: {{ .Values.postgres.port }}
      protocol: TCP
