apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-short-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: api-short
          image: antonlarichev/short-api:v1.0
          resources:
            limits:
              memory: '528Mi'
              cpu: '200m'
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: short-api-secret
          volumeMounts:
            - name: test
              mountPath: /etc/test
              readOnly: true
      volumes:
        - name: test
          configMap:
            name: demo-config
