apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-short-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      labels:
        components: frontend
    spec:
      containers:
        - name: app-short
          image: antonlarichev/short-app:v1.4
          resources:
            limits:
              memory: '228Mi'
              cpu: '200m'
          ports:
            - containerPort: 80
